// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckStatus(arg1) {
  return window['go']['backend']['App']['CheckStatus'](arg1);
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function Disconnect(arg1) {
  return window['go']['backend']['App']['Disconnect'](arg1);
}

export function DisconnectAll() {
  return window['go']['backend']['App']['DisconnectAll']();
}

export function ExportCSV(arg1, arg2) {
  return window['go']['backend']['App']['ExportCSV'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetSystemLanguage() {
  return window['go']['backend']['App']['GetSystemLanguage']();
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function LoadPlcLinks(arg1) {
  return window['go']['backend']['App']['LoadPlcLinks'](arg1);
}

export function LoadTags(arg1) {
  return window['go']['backend']['App']['LoadTags'](arg1);
}

export function SavePlcLinks(arg1, arg2) {
  return window['go']['backend']['App']['SavePlcLinks'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function SaveTags(arg1, arg2) {
  return window['go']['backend']['App']['SaveTags'](arg1, arg2);
}

export function StartPolling(arg1) {
  return window['go']['backend']['App']['StartPolling'](arg1);
}

export function StopPolling() {
  return window['go']['backend']['App']['StopPolling']();
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}
