// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckStatus(arg1) {
  return window['go']['backend']['App']['CheckStatus'](arg1);
}

export function ClearHistory() {
  return window['go']['backend']['App']['ClearHistory']();
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function Disconnect(arg1) {
  return window['go']['backend']['App']['Disconnect'](arg1);
}

export function DisconnectAll() {
  return window['go']['backend']['App']['DisconnectAll']();
}

export function ExportCSV(arg1) {
  return window['go']['backend']['App']['ExportCSV'](arg1);
}

export function GetHistoryRange(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetHistoryRange'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetSystemLanguage() {
  return window['go']['backend']['App']['GetSystemLanguage']();
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function LoadPlcTagSettings(arg1) {
  return window['go']['backend']['App']['LoadPlcTagSettings'](arg1);
}

export function LoadSettingsFile(arg1) {
  return window['go']['backend']['App']['LoadSettingsFile'](arg1);
}

export function RecordSample(arg1, arg2, arg3) {
  return window['go']['backend']['App']['RecordSample'](arg1, arg2, arg3);
}

export function SavePlcTagSettings(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SavePlcTagSettings'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function SaveSettingsFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveSettingsFile'](arg1, arg2);
}

export function StartPolling(arg1) {
  return window['go']['backend']['App']['StartPolling'](arg1);
}

export function StopPolling() {
  return window['go']['backend']['App']['StopPolling']();
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}
